### ISSUE TITLE
ブートできないエラー

### ISSUE THREAD

**Issue by yushoyamaguchi** [cupnes/x86_64_jisaku_os_samples#2]
A01_poiboot ディレクトリにて
```
make deploy
```
を行い、poiboot_qemutest.confの内容をそのままpoiboot.confとしてfsディレクトリに設置した上で、
020-fillをはじめとした各kernelのディレクトリにて```make run```をしたところ、添付のスクリーンショットのところで無限ループとなっているようでした。
![poiboot](https://github.com/cupnes/x86_64_jisaku_os_samples/assets/50731798/62c1daa9-9c67-457f-9579-c49154e005cf)
デバッグプリントした結果、
https://github.com/cupnes/x86_64_jisaku_os_samples/blob/master/A01_poiboot/libuefi/mem.c#L79
ここで止まっているようなのですが、考えられる原因等はありますでしょうか？

qemuは
```
qemu-system-x86_64 -m 4G -bios OVMF.fd -hda fat:rw:../fs -boot c
```
このコマンドで立ち上げております。

**Comment by cupnes** [comment]
お試しいただきありがとうございます。そして、うまく動かずすみません。

調べてみた所、以下のことが分かりましたので、お伝えさせていただきます。

繰り返し画面に出力されている`GetMemoryMap:8000000000000005`の`8000000000000005`の部分は、`GetMemoryMap`関数の戻り値(`status`変数)を16進数で表記したものです。

この`GetMemoryMap`関数はUEFIの関数であり、その仕様についてはUEFIの仕様書を参照します。ここでは以下を参照しました。

https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf

この仕様書のP.169以降に`GetMemoryMap`関数の仕様が書かれています。戻り値についてはP.173の「Status Codes Returned」に書かれています。

UEFIの関数はステータスコード(UEFIの仕様書内では`EFI_STATUS`という型で表されます)と呼ばれる定数を返すのですが、P.173の「Status Codes Returned」には定数名で示されているため、`8000000000000005`という値がどれに合致するのかがこれでは分かりません。

ステータスコードの仕様についてはP.2194以降の「Appendix D - Status Codes」に書かれています。

まず、「Table D-1 EFI_STATUS Code Ranges」を見ると、「Supported 64-bit Architecture Ranges」が「0x8000000000000000-0x9fffffffffffffff」の時、それはエラーコードであることが分かります。

そして、「Table D-3 EFI_STATUS Error Codes (High Bit Set)」を見ると、「Value」が「5」の「Mnemonic」は「EFI_BUFFER_TOO_SMALL」であることが分かります。

即ち、`GetMemoryMap`関数は「EFI_BUFFER_TOO_SMALL」というエラーステータスを返していたことが分かります。

ここで改めてP.173の「Status Codes Returned」を見てみると、「EFI_BUFFER_TOO_SMALL」について以下のように書かれています。

> The MemoryMap buffer was too small. The current buffer size needed to
> hold the memory map is returned in MemoryMapSize.

`MemoryMap`バッファが小さすぎるとのことで、必要なバッファサイズは`MemoryMapSize`で返される、とのことです。

P.169に書かれている`GetMemoryMap`関数のプロトタイプ宣言を見ると分かりますが、`MemoryMap`は`GetMemoryMap`関数の第2引数、`MemoryMapSize`は第1引数です。「必要なバッファサイズは`MemoryMapSize`で返される」とのことなので、`GetMemoryMap`関数から戻ってきた後、`MemoryMapSize`にどんな値が入っているのかが気になります。

ソースコードとしては、ご指摘いただいた箇所の少し上の↓の箇所で`GetMemoryMap`関数を呼び出しています。

https://github.com/cupnes/x86_64_jisaku_os_samples/blob/9310f8e/A01_poiboot/libuefi/mem.c#L76-L78

↑で`GetMemoryMap`関数を呼び出す際に第1引数に指定している`mmap_size`を、`GetMemoryMap`関数から戻ってきた直後に出力してみると、どんな値が入っていますでしょうか？

なお、poibootでの値の出力方法は`check_warn_error`関数の実装などを参考にしてみてください。`puth`関数(指定された値を16進数で出力する関数)を使用すると良いかと思います。

　

順を追ってご確認いただきたく長文ながら上記の通り説明させていただきましたが、結論としては、↓で設定している定数`MEM_DESC_SIZE`の値(メモリマップを格納する領域のサイズ)を大きくする必要があるのかと思います。

https://github.com/cupnes/x86_64_jisaku_os_samples/blob/9310f8e/A01_poiboot/libuefi/mem.c#L5

↑で`MEM_DESC_SIZE`を大きくすると、↑の7行目で定義している通り、`mem_desc`という配列もそれに従って大きくなります。

そして、↓の箇所で変数`mmap_size`に`MEM_DESC_SIZE`を設定しており、この`mmap_size`と`mem_desc`を用いて`GetMemoryMap`関数を呼び出しています。

https://github.com/cupnes/x86_64_jisaku_os_samples/blob/9310f8e/A01_poiboot/libuefi/mem.c#L75

定数`MEM_DESC_SIZE`の値をどれくらい大きくすると良いかは、前述の通り`GetMemoryMap`関数から戻った後の`mmap_size`の値をご確認いただくのが良いかと思います。

**Comment by yushoyamaguchi** [comment]
丁寧に調査してコメント頂き、本当にありがとうございます。
大変助かりました。

![required_mem_size](https://github.com/cupnes/x86_64_jisaku_os_samples/assets/50731798/d3410665-8ac4-4766-a28b-80f7f9062390)
必要なメモリサイズとして0x1980が返ってきたので、mem_desc_sizeを4800+(0x1980)より大きいに9600に設定したところ、該当のエラーは解消されました。
![boot0527](https://github.com/cupnes/x86_64_jisaku_os_samples/assets/50731798/24ded08d-0272-4eca-9847-adf6a58df5e4)
statusが別のエラー(EFI_INVALID_PARAMETER ?)になっているように見えたのですが、こちらについては見覚えのあるエラーだったりしますでしょうか？
(DocumentにはMemoryMapがNULLになっている可能性があると書いてありましたが、そうなっていないことは確かめました。)


**追伸**
大神さんが公開してくださっている資料とソースコードは、低レイヤの勉強をする上でいつも大変参考にさせていただいております。
公開していただき、本当にありがとうございます。
(自分だけでなく知人・友人でも参考にしているという人を多く知っています。)
本の購入やスポンサーなど、微力ですが機会があれば何か恩返しができればなと考えております。
これからも、よろしくお願いいたします。

**Comment by cupnes** [comment]
ご確認いただきありがとうございます！
ただ、一筋縄ではいかないですね・・。
加えて、後述しますが、こちらで調べてみました限りでも確たる事は分かりませんでした。(すみません。)
一応考えられることを記載いたしますので、参考にしていただければと思います。

ご確認いただいた通り、`ExitBootServices`関数がEFI_INVALID_PARAMETERを返していますね。
先述のUEFIの仕様書で、`ExitBootServices`関数の説明の「Status Codes Returned」(P.226)の記述によると、
`ExitBootServices`関数が返すEFI_INVALID_PARAMETERには「`MapKey` is incorrect.」という意味があるそうです。

`MapKey`は`ExitBootServices`関数の第2引数です。`ExitBootServices`関数の呼び出しは↓で行っています。

https://github.com/cupnes/x86_64_jisaku_os_samples/blob/9310f8e/A01_poiboot/libuefi/mem.c#L81

↑で`ExitBootServices`関数の第2引数に変数`map_key`を渡しています。仕様書の説明によればこの変数の値が正しくないということのようです。

この`map_key`は、`GetMemoryMap`関数の第3引数にポインタで指定している事からも分かる通り、この変数への値の設定は`GetMemoryMap`関数で行われます。

ただ、`check_warn_error`関数を突破して`ExitBootServices`関数の実行に至っていることから`GetMemoryMap`関数は正常に終了していると思われ、それであれば`map_key`には正しい値が格納されているはずです。
(もしかしたら`GetMemoryMap`関数が正常終了していても第3引数へ不正な値が設定されてしまうことがあるのかもしれませんが、仕様書を私が確認する限り、そのような事はなさそうでした。)

そして、ここからは私としても「これで解決するか分からない」といった所の話で申し訳ないのですが、
仕様書のP.225に以下の記述があります。

> A UEFI OS loader must ensure that it has the system's current memory map at the time it calls ExitBootServices(). This is done by passing in the current memory map’s MapKey value as returned by EFI_BOOT_SERVICES.GetMemoryMap(). Care must be taken to ensure that the memory map does not change between these two calls. It is suggested that GetMemoryMap() be called immediately before calling ExitBootServices().

「`GetMemoryMap`関数は`ExitBootServices`関数の直前で呼び出すことが推奨される」とのことです。

現状の実装でもそのようにしているつもりではあるのですが、「何らかのタイミングの問題が生じている(?)」などを考えると、例えば以下のような対処で何か進展があるかもしれません。

■ 案. `GetMemoryMap`の直後で`ExitBootServices`を呼び出す事を繰り返す

libuefi/mem.cの`exit_boot_services`関数の実装について、`GetMemoryMap`関数の戻り値確認を`check_warn_error`関数で行う事はあきらめて、以下の流れで実装し直すイメージです。

1. `GetMemoryMap`関数呼び出し
2. (`GetMemoryMap`関数の戻り値確認はせずに、)`ExitBootServices`関数呼び出し
3. `ExitBootServices`関数の戻り値が0(EFI_SUCCESS)でない場合は1.に戻る

　

なお、これは結果としては問題無く、単なる誤記かと思われますが、

> 必要なメモリサイズとして0x1980が返ってきたので、mem_desc_sizeを4800+(0x1980)より大きいに9600に設定したところ、該当のエラーは解消されました。

4800(10進数)と0x1980(10進数で6528)の和は11328(10進数)であるため、9600(10進数)では11328(10進数)よりは小さいです。

ただ、9600(10進数)であれば必要なメモリサイズとして返ってきた0x1980(10進数で6528)よりは大きいので問題は無いと思われます。

　

追伸への返信

応援のお言葉誠にありがとうございます！
私の趣味の活動ではありますが、そのように言っていただけると本当に励みになります。

ただ、近年はPCを趣味の対象のハードウェアとすることが無くなってしまい、
この度のご質問をきっかけに調べ直す形となってしまっているため、
もしかしたら的を得た回答ができていないかもしれない点は申し訳ありません。

**Comment by yushoyamaguchi** [comment]
提案していただいたような実装にしたところ、無事030まではブートできました。
ありがとうございました！
https://github.com/yushoyamaguchi/x86_64_jisaku_os_samples/tree/yama_dev1
また、デバッグの際の手順や考え方なども、非常に参考になりました。
(040_intr 以降は青画面が半分くらい出てきたくらいでブートが初めからになるというのが繰り返される症状がありますが、それはどちらかというとカーネルの方の問題のような気もするので、ブート問題は解決できたと思います。)

mem_desc_sizeの足し算に関しては、恥ずかしながら完全に計算間違いをしておりました。
ご指摘ありがとうございます。

最後にまた質問になってしまい申し訳ないですが、このカーネルをgdb+qemuでデバッグしてkernel内の関数にブレークポイントを張りたい時、シンボルファイルとして指定すべきファイルはどのファイルでしょうか？(kernel.binを指定しようとすると、`not in executable format: file format not recognized` と言われてしまいました。)

**Comment by cupnes** [comment]
030までは無事ブートできたとのことで良かったです！
フルスクラッチの開発であることもあり、色々と原始的なデバッグ方法になってしまいますが、参考にしていただければ幸いです。

なお、gdbについては、こちらのOSの開発の際に使用しておらず、申し訳ありませんが具体的な方法をご案内することができません・・・。

各ディレクトリのMakefileを見ていただくと分かりますが、
リンカ(ldコマンド)の`-Map`オプションでkernel.mapというファイルへシンボル情報を出力するようにしています。

ただ、これはプレーンテキストのファイルで、カーネルの関数がどのアドレスかを自分で確認するために用いていたため、
gdbでこのファイルを読めるのかは分かりません・・。

また、お試しされた際のエラーメッセージにも出ている通り、kernel.binはバイナリフォーマットを
各ディレクトリのリンカスクリプト(kernel.ld)で設定している独自なものなので、kernel.bin自体をgdbが解釈することはできません。

デバッグ方法としては、これまた原始的な方法になってしまいますが、
例えば「青画面が半分くらい出てきたくらいでブートが初めからになるというのが繰り返される」という症状であれば、
カーネルの処理の「どこか」を実行した拍子にリセット的な挙動に陥るのかと思われますので、
その「どこか」を突き止めるために、カーネルの処理の始めからある程度の所に`while (1);`といった無限ループを追加してみる、
という方法が考えられます。

無限ループを追加した状態で実行した結果、
「ブートが初めからになる」挙動に陥らなくなるなら、無限ループを追加した行より後の行に原因があると考えられます。
そうではなく、無限ループを追加しても「ブートが初めからになる」挙動に陥るなら、無限ループを追加した行より手前の行に原因があると考えられます。

原始的な方法ですみませんが、例えばこのような方法でデバッグを行うことができます。

その他にも、QEMU内蔵の「QEMUモニタ」という機能も使えます。
こちらについてはウェブ上に色々と情報がありますので、検索などしていただければと思いますが、実行中のレジスタやメモリを見ることができます。
それにより、例えば`info registers`というコマンドで出力される現在のレジスタ値の一覧の中のEIPレジスタの値から、今どのアドレスを実行中かが分かり、
前述のkernel.mapと照らし合わせることで、そのアドレスがどの関数の中なのかが分かります。

**Comment by yushoyamaguchi** [comment]
なるほど、参考にしてデバッグさせていただきます。
数々の質問に丁寧に答えてくださり、本当にありがとうございました。

追記
教えていただいた方法でデバッグしたところ、
https://github.com/cupnes/x86_64_jisaku_os_samples/blob/master/040_intr/x86.c#L43
この部分でエラーが起こっているようでした。
DS,SSレジスタに0x10ではなく0を入れるようにすると、DS,SSのところはパスするようになりました。(まだCSレジスタのところでエラーは出ています。)
MikanOSのコードで出ている値を参考に、何も理解せずこの値にしたのですが、このあたりのレジスタにどのような値を入れるべきかが書いてある仕様書などはあるのでしょうか...
(MikanOSでは、DSには0,SSには0x10を入れているようでした。)

**Comment by cupnes** [comment]
着々と進んでいるようで本当に良かったです！

x86系CPUの仕様はIntelが公開している下記のマニュアルにまとめられています。
(自作OSの界隈では「Intel SDM」などと呼ばれていたりして、よく参照されます。)

Intel® 64 and IA-32 Architectures Software Developer Manuals
https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html

Volume 1〜4で5000ページを超える膨大なマニュアルのため、
PDF内をキーワードで検索したりして、気になるところを読んでみるのが良いと思います。

ちなみに、DS・SS・CSといったセグメントレジスタについては、Volume 1の「3.4.2 Segment Registers」辺りに書かれています。
そして少しややこしいですが、セグメントレジスタへの設定値である「セグメントセレクタ」の仕様は同じくVolume 1の「3.7.4 Specifying a Segment Selector」辺りに書かれています。

なお、Volume 1の「3.7.4.1 Segmentation in 64-Bit Mode」に書かれていますが、64ビットモードでは基本的にセグメンテーションは無効化されているとのことです。
そのため、64ビットモードでセグメントレジスタを設定した場合の挙動に明に仕様は無く、実装依存(QEMUであればQEMUがどのようにエミュレーションしているか次第)なのかもしれないですね。
その意味では、「セグメントレジスタへどのような値を入れるべきか」といった事は64ビットモードの場合については明に書かれてはいないかもしれません。(今のSDMを詳しく読んだわけではないのではっきりとは言えませんが。)

このリポジトリでサンプルとして公開しているOSは、今から6年程も前に作っていたOSであり、
当時としては、一応、セグメンテーションが機能してしまっても動くように、
「GDT(Global Descriptor Table)」へ最低限のセグメントデスクリプタの設定を行い、
セグメントレジスタへはそれらのセグメントデスクリプタを設定する
といった、セグメンテーションの設定を行うようにしています。

ただ、現在のQEMUではセグメントレジスタへ0以外の意味のある値を設定すると
むしろ不必要にセグメンテーション機能が動いてしまって良くないのかもしれないですね。
(これも推測であり、はっきりとした事が言えず申し訳ありませんが・・。)

**Comment by yushoyamaguchi** [comment]
なるほど、ありがとうございます。
もう少し探ってみます。

**Comment by yushoyamaguchi** [comment]
何度もすみません。
別の実機2で試して見たところ、写真のようにブートが途中で止まりました。
気になってhead.bss_sizeの値を表示してみたところ、ものすごく大きな値になっているように見えました。
https://github.com/yushoyamaguchi/x86_64_jisaku_os_samples/blob/efa83a89cfa6911f77801fbb2b776b1ee066dbe3/A01_poiboot/poiboot.c#L84
<img width="493" alt="boot2" src="https://github.com/cupnes/x86_64_jisaku_os_samples/assets/50731798/aed8c4f3-5f63-4fad-90ad-3418a387a121">

元の実機1で該当箇所の直後にhltを入れて見てみたところ、head.bss_sizeには0が入っていました。
![intended_hlt](https://github.com/cupnes/x86_64_jisaku_os_samples/assets/50731798/b75d9f96-1459-4f68-8754-f6320622a365)

実機2の方でhead.bss_sizeに0を代入してみたところ、一応該当箇所はパスできました。(その後セグメントレジスタのところでエラーが起きているのは変わっていません。)
https://github.com/yushoyamaguchi/x86_64_jisaku_os_samples/blob/420b7077c93d7018f7bcb813e285a4544fe25d8a/A01_poiboot/poiboot.c#L86

そこで質問なのですが、

1. head.bss_sizeはどのくらいの値になるのが正常なのでしょうか？
(自分には0も大きい数も不自然に感じました。)
2. この部分が原因で、カーネルの処理に入ってからのセグメントレジスタ周りでのエラーに繋がることは直感的にありそうなのでしょうか？

以上、よろしくお願いいたします。

**Comment by cupnes** [comment]
(何ゆえそのような症状が出ているのか謎ですが・・。)
ご質問の2点について回答させていただきます。

まず1.について、
head.bss_sizeにはkernel.binのbssセクションのサイズを設定するようにしていますので、
どのくらいの値になるのが正常かというと、それはkernel.bin次第ではありますが、
このリポジトリで生成されるkernel.binに関しては、ざっと確認してみた所、数十〜数キロバイトといった所でした。
なお、0はあり得る値です。例えば020_fillは、そもそもグローバル変数やスタティック変数等を使用していないので、
bssセクションに配置されるものが無く、サイズが0となります。

次に2.について、
カーネルの処理に入ってからのセグメントレジスタ周りの処理は
bssセクションに配置されるようなグローバル変数等を使用していないため、
head.bss_sizeの部分が原因でエラーに繋がることは直感的には考え難いです。

なお、head.bss_sizeはpoibootがkernel.binをロードする際に
メモリ上でbssセクションに使用する領域を予め0で初期化する処理で「初期化するサイズ(bssセクションのサイズ)」として使用しています。
そのため、例えばkernel.binの実際のbssセクションのサイズに関わらずhead.bss_sizeに0を設定してしまうと、
カーネルの処理に入った後、0で初期化されているべきグローバル変数やスタティック変数等が初期化されていないことになり、
思わぬ誤動作に繋がることはありそうです。

**Comment by yushoyamaguchi** [comment]
> ざっと確認してみた所、数十〜数キロバイトといった所でした

なるほど、では上の`00554E4700000005`というのはやはりおかしそうですね。(なぜこんなことになってるのかは皆目見当もつきませんが...)

head.bss_sizeの件もありがとうございます!
この領域は、カーネルの実行ファイルにおけるbssの領域のことだったのですね。
なかなか苦戦しており、低レイヤの難しさを感じています...

**Comment by cupnes** [comment]
はい、何かおかしなことになっていそうではあるのですが、
なぜそのようなことになっているのか私にも見当がつかず。。
お力になれず、すみません・・。

**Comment by yushoyamaguchi** [comment]
いえいえ、たくさんの質問に丁寧に答えてくださり、本当にありがとうございました。
大変勉強になりました。
